### ISSUE TITLE
why provide a client_secret

### ISSUE THREAD

**Issue by munazmv** [Uber5/react-pkce#1]
i thought the whole point of pkce flow is to avoid exposing the client_secret in public apps.

**Comment by Chris927** [comment]
Hi @munazmv we chose to implement it this way, as our token endpoint requires authentication (e.g. via the client_secret), unless the implicit flow is allowed.

The [pkce spec](https://tools.ietf.org/html/rfc7636#section-4.5) requires an *additional* parameter, the `code_verifier`, which IMU means that [semantics of the token endpoint](https://tools.ietf.org/html/rfc6749#section-4.1.3) should not change, i.e. if you want to get a token for a code, you must authenticate: "... or the client was issued client credentials ... the client MUST authenticate".

Yes, the `client_secret` is now exposed, but as long as you follow the other security measures within OAuth2 (client allows one redirect_uri only, etc.), this is a reasonable solution, I believe.

Maybe the `client_secret` should be optional, so that if the provider does not require authentication on the token endpoint, the package can still be used?

What is your use case? What provider are you using?

**Comment by Chris927** [comment]
Resolved in v0.9.9.
