### ISSUE TITLE
Aws support for token retrieval with 'application/x-www-form-urlencoded'

### ISSUE THREAD

**Issue by remcobosman** [Uber5/react-pkce#2]
Dear Uber5,

I wanted to use this package for authentication in AWS. However I ran into two problems.

One is that the return uri was missing a slash in the setup at the AWS end, so I would like to be able to configure the return uri (like the client id, etc)

Next problem was that Aws actually does not support application/json as the content type and json as the payload (weird but something I cannot change). So I need support for "application/x-www-form-urlencoded".

I would be more than happy to post a PR, as I have the changes running locally. Are there any options for me to submit this?

Regards,

Remco Bosman

**Comment by Chris927** [comment]
Hi Remco

We are more than happy to accept a pull request for this.

As soon as you submit a pull request, I'll review it and let you know any feedback.

Best regards,
Chris

**Comment by remcobosman** [comment]
I think I have not enough privileges to push my new branch. 

Regards,

Remco

**Comment by Chris927** [comment]
Hi Remco

You cannot push a new branch into this repo.

The way to do this:

- Fork the whole repository (fork button at the top right), so that you have your own repo under your name.
- Push your new branch into the forked repository.
- Create a pull request, requesting your new branch to be merged into this repo.

Hope this helps?

Best regards,
Chris

**Comment by remcobosman** [comment]
Yes that helped. I have created the PR. Let me know if anything requires more attention.

Regards,

Remco Bosman
